### ISSUE TITLE
FAQ entry

### ISSUE THREAD

**Issue by ErikDeBruijn** [YouMagine/YM-php-sdk#2]
I'm getting:
![image](https://cloud.githubusercontent.com/assets/191236/6749139/96a73486-ceed-11e4-96bc-c58e32ffcb68.png)
What to do if I get this? Can we add this to the FAQ? Can we make the explanation more verbose on YouMagine? Or does it need to be on test.YouMagine.com until the next release?

**Comment by martijnversluis** [comment]
When did you get this message?

**Comment by ErikDeBruijn** [comment]
On Fri Mar 20 10:55:07 2015 I gave the API example a try. Right after clicking the button I got it.

I also get it when I try it again right now.

**Comment by martijnversluis** [comment]
Can't reproduce it. Which exact URL is it?

**Comment by ErikDeBruijn** [comment]
It generates this URL: `http://youmagine.com/integrations/phpexample/authorized_integrations/new?redirect_url=http%3A%2F%2Flocalhost%3A8000%2Fyoumagine-php-api-example.php%3Fpage%3Dauthorization%26event%3Dredirected&deny_url=http%3A%2F%2Flocalhost%3A8000%2Fyoumagine-php-api-example.php%3Fpage%3Dauthorization%26event%3Ddenied`

**Comment by ErikDeBruijn** [comment]
To reduce at least one redirect it's better to link to `https://www.youmagine.com/*` instead of `http://youmagine.com/*`.

**Comment by martijnversluis** [comment]
Could it be a session problem in your browser? When visiting this URL, I am forwarded to https://www.youmagine.com/users/martijn-youmagine/authorized_integrations, the page on which I can authorize the integration.

When logging out before visiting the URL, I get: 
![screen shot 2015-03-23 at 16 07 13](https://cloud.githubusercontent.com/assets/1219904/6782835/c3334a72-d176-11e4-95f0-5277face924f.png)

The reason the SDK refers to http://youmagine.com/*, is because the SDK can also consume an API running on localhost.

**Comment by ErikDeBruijn** [comment]
When using incognito I get redirected to the login page. After login I get `You are not authorized to access this page.`
Let's give this a try tomorrow when you're in the office. Will be much faster!
