### ISSUE TITLE
A Reflected XSS vulnerability in this sdk

### ISSUE THREAD

**Issue by jgj212** [YouMagine/YM-php-sdk#5]
Hello:
I found a Reflected XSS vulnerability in this sdk.

The vulnerability exists due to insufficient filtration of user-supplied data in 'user_slug_or_id' HTTP _GET parameter that will be passed to “YM-php-sdk-master/examples/retrieve_designs_with_context.php”. The infected source code is line 13,  there is no protection on $_GET["user_slug_or_id"]; If $_GET["user_slug_or_id"] contains evil js code, line 13 will trigger untrusted code to be excuted on the browser side
>
![code1](https://cloud.githubusercontent.com/assets/1484292/23252965/b4e8dfee-f9ed-11e6-8aea-fe3d1365236e.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/YM-php-sdk-master/examples/retrieve_designs_with_context.php?user_slug_or_id="><script>alert(1);</script><"

The follow screenshot is the result to click the upper url ( win7 sp1 x64 + firefox 51.0.1 32bit ):
>
![sc](https://cloud.githubusercontent.com/assets/1484292/23252972/c08a1642-f9ed-11e6-95a0-3660bb367ddc.png)

Discoverer: ADLab of Venustech

**Comment by 99linesofcode** [comment]
Dear Haojun,

Thank you for taking the time to peer review our code. It means a lot to us.

The code you are referring to is meant to serve as an example. A way to show other programmers how they could interact with the `youmagine.php` wrapper for our API.
We expect any programmer working on an application that accepts user input to be aware of the dangers and make sure that such input is sanitised before being put to use.

Because this is essentially a non issue and maintaining the example code is not high on our list of priorities, I am closing this issue.

If you find any vulnerabilities in our API or this wrapper class, please do not hesitate to open another ticket.

With kind regards,

Jordy
